# Site settings
email:
baseurl: ""
paginate: 4
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: Lucas Andrade
description:
url: ""
twitter_username:
default_img:

# Profile settings
name: "Lucas Andrade"
profile_img: /assets/img/me.jpg
profile:
social:
  at: mailto:lucasandradedeveloper@gmail.com
  github: https://gitbub.com/lucandrade
  linkedin: https://br.linkedin.com/in/lucas-andrade-39b901b1
# navigation
navigation:
- text: Posts
  url: /
- text: Categories
  url: /categories/
  contains: /category/
- text: About
  url: /about/

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
