# Site settings
email: lucasandradedeveloper@gmail.com
baseurl: ""
paginate: 4
paginate_path: "/blog/page-:num"
google_analytics: UA-90095895-1

# SEO settings
title: Lucas Andrade
description:
url: "https://lucandrade.github.io"
facebook_id: 100001470977759
twitter_username:
default_img: https://lucandrade.github.io/assets/img/me.jpg
default_img_width: 450
default_img_height: 676

# Profile settings
name: "Lucas Andrade"
profile_img: /assets/img/me.jpg
profile: "Thats me!"
social:
  at: mailto:lucasandradedeveloper@gmail.com
  github: https://gitbub.com/lucandrade
  linkedin: https://br.linkedin.com/in/lucas-andrade-39b901b1
# navigation
navigation:
- text: Projects
  url: /
  contains: /post/
- text: About
  url: /about/

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
