# Site settings
email:
baseurl: ""
paginate: 4
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: Lucas Andrade
description:
url: ""
twitter_username:
default_img: https://lucandrade.github.io/assets/img/me.jpg

# Profile settings
name: "Lucas Andrade"
profile_img: /assets/img/me.jpg
profile: "Thats me!"
social:
  at: mailto:lucasandradedeveloper@gmail.com
  github: https://gitbub.com/lucandrade
  linkedin: https://br.linkedin.com/in/lucas-andrade-39b901b1
  twitter: https://twitter.com/delucalabs
# navigation
navigation:
- text: Blog
  url: /
  contains: /post/
- text: Categories
  url: /categories/
  contains: /category/
- text: About
  url: /about/

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
